# Generated by Django 3.2.5 on 2021-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(default='currency', max_length=200),
            preserve_default=False,
        ),
    ]
