# Generated by Django 3.2.5 on 2021-08-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkprice', '0002_currency_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='yesterday_price',
        ),
        migrations.AddField(
            model_name='currency',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='currency', max_length=200),
        ),
    ]
