# Generated by Django 3.2.6 on 2021-08-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
