# Generated by Django 3.2.6 on 2021-08-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/profile_default_img', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='message',
            field=models.CharField(default='NONE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='NONE', max_length=20, null=True, unique=True),
        ),
    ]
