# Generated by Django 3.2.6 on 2021-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_auto_20210822_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/profile_default_img.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='message',
            field=models.CharField(default='MESSAGE NOT SETTED', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='NICKNAME NOT SETTED', max_length=20, null=True, unique=True),
        ),
    ]
